### ISSUE TITLE
More test

### ISSUE THREAD

**Issue by vojty** [c-sp/gameboy-test-roms#27]
Hello 

This is a great collection of tests.

I found the following tests that I use for testing my emulator and that are missing from your list:

- https://github.com/EricKirschenmann/MBC3-Tester-gb
- https://github.com/Powerlated/TurtleTests
- https://github.com/Hacktix/scribbltests

Would you like me to add these as well? I can make a PR.

**Comment by c-sp** [comment]
Hi @vojty 

sure, feel free to create a PR. If you need any help, I will gladly assist.

**Comment by vojty** [comment]
here is the first PR https://github.com/c-sp/gameboy-test-roms/pull/28
Unfortunately, I couldn't run `assemble-all.sh` locally (`wla-dx` installation fails) so hopefully it works.

**Comment by vojty** [comment]
Btw when updating dependencies in my emulator (https://github.com/vojty/feather-gb/) yesterday, I realized that each test ROM requires a certain version of `rgbds` or `wla-dx` and the latest versions don't work. It was pretty painful to find out the right versions and make it build again. Moreover, I feel like this happens to me every year...

This got me thinking about specifying dependencies for each test ROM (or rather each repository) and using Docker for the build. Would you be interested in such a change?

**Comment by c-sp** [comment]
> here is the first PR #28 Unfortunately, I couldn't run `assemble-all.sh` locally (`wla-dx` installation fails) so hopefully it works.

The wla-dx issue is indeed quite annoying. I'm not sure since when exactly it occurrs, but some of the last macOS updates broke it for me. I have been thinking of patching wla-dx locally, maybe I should look into this again.

**Comment by c-sp** [comment]
> Btw when updating dependencies in my emulator (https://github.com/vojty/feather-gb/) yesterday, I realized that each test ROM requires a certain version of `rgbds` or `wla-dx` and the latest versions don't work. It was pretty painful to find out the right versions and make it build again. Moreover, I feel like this happens to me every year...
> 
> This got me thinking about specifying dependencies for each test ROM (or rather each repository) and using Docker for the build. Would you be interested in such a change?

Right, depending on a test suite's age current compilers won't work any more. Using dockerized compilers sounds great, I must admit I never thought of that :wink:

**Comment by c-sp** [comment]
Are you working on TurtleTests or scribbltests? Maybe I can do the other one.

**Comment by vojty** [comment]
I haven't started working on either of those. Just let me know which one you'll choose so I can work on the other one.

**Comment by c-sp** [comment]
Alright, I'll do the TurtleTests.

**Comment by c-sp** [comment]
TurtleTests are finished. If you want, I can do the scribbltests too 😉

**Comment by vojty** [comment]
I'm little bit busy right now so go ahead 👍

**Comment by c-sp** [comment]
Scribbltests added as well.

v7.0 has been released, thanks for your help!
If there's anything wrong, feel free to reopen this issue 😉

**Comment by vojty** [comment]
Thanks! I'll migrate my test suite to use this repository (hopefully) soon and verify it
